name: CD
on:
  push:
    branches:
      - main
jobs:
  build:
      name: Deploy
      runs-on: ubuntu-latest
      steps:
        - name: Connect to Google Cloud VM
          uses: google-github-actions/setup-gcloud@v0
          with:
            project_id: ${{ secrets.PROJECT_ID }}
            service_account_key: ${{ secrets.SERVICE_ACCOUNT_KEY }}
            export_default_credentials: true
      
        - name: Deploy to Google Cloud VM
          run: gcloud compute ssh rafafergon@instance-1 --zone=europe-southwest1-a --command="cd /home/rafafergon/DPP_Frontend; git pull; sudo fuser -k 5173/tcp; /home/rafafergon/.nvm/versions/node/v18.16.0/bin/npm run build; /home/rafafergon/.nvm/versions/node/v18.16.0/bin/npm run preview -- --port 5173 --host &"

